# Generated by Django 4.2.9 on 2025-05-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(null=True, upload_to='pokemon_images'),
        ),
    ]
