# Generated by Django 4.2.9 on 2025-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(null=True, upload_to='trainer_images'),
        ),
    ]
